// Action Types for logs
export const ADD_LOG = 'ADD_LOG';
export const DELETE_LOG = 'DELETE_LOG';
export const UPDATE_LOG = 'UPDATE_LOG';
export const GET_LOGS = 'GET_LOGS';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const SEARCH_LOGS = 'SEARCH_LOGS';
export const CLEAR_LOGS = 'CLEAR_LOGS';
export const SET_LOADING = 'SET_LOADING';
export const LOGS_ERROR = 'LOGS_ERROR';
// Action Types for logs
export const ADD_DEVELOPER = 'ADD_DEVELOPER';
export const DELETE_DEVELOPER = 'DELETE_DEVELOPER';
export const GET_DEVELOPERS = 'GET_DEVELOPERS';
export const DEVELOPER_ERROR = 'DEVELOPER_ERROR';
